name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-src: 'https://github.com/roothide/theos'
          theos-sdks: 'https://github.com/xybp888/iOS-SDKs'

          orion: 'false'
      - name: Build and Install ChOma
        run: |
          cd ChOma
          sudo make install
          sudo cp output/tests/* /usr/bin
      - name: Build kfdfun
        run: |
          cd ../tools
          make
          cd ../app
          ./build.sh
      - name: Create github release
        id: upload-release
        uses: actions/upload-release-assets@v2
        with:
          files: |
            packages/kfdmineek.tipa
